(() => {
  "use strict";
  const { request, config, setDemoBadge, escapeHtml, formatYen, formatDate, appendQuery, showToast } = window.DPRO;
  const $=(id)=>document.getElementById(id); let token="", recommendation=null;
  const responseLabels={interested:"興味があります",hold_requested:"取り置き希望",consultation_requested:"相談したい",purchased:"購入しました",declined:"今回は見送る"};
  document.addEventListener("DOMContentLoaded",()=>{ setDemoBadge($("demoBadge")); document.querySelector("[data-home-link]").href=appendQuery("index.html"); $("recommendConsult").href=appendQuery(config.CONSULTATION_PAGE||"consultation.html"); $("recommendCatalog").href=appendQuery(config.CATALOG_PAGE||"catalog.html"); document.addEventListener("click",respond); load(); });
  async function load(){ token=new URLSearchParams(location.search).get("recommendation_token")||new URLSearchParams(location.search).get("token")||""; if(!token)return fail("おすすめ提案の共有情報がありません。店舗から届いたURLを開き直してください。"); try{const d=await request(`/recommendations/view?token=${encodeURIComponent(token)}`); recommendation=d.recommendation; render(); $("recommendApp").hidden=false;}catch(e){fail(e.message)}finally{$("recommendLoading").hidden=true;} }
  function render(){ $("recommendTitle").textContent=recommendation.title||"あなたへのおすすめ"; $("recommendMessage").textContent=recommendation.customer_message||"お客様のご希望に合わせて、スタッフが商品を選びました。"; $("recommendNo").textContent=recommendation.recommendation_no||"PERSONAL"; $("recommendExpiry").textContent=recommendation.expires_at?`公開期限：${formatDate(recommendation.expires_at)}`:""; $("recommendItems").innerHTML=(recommendation.items||[]).map(itemCard).join("")||'<div class="cos-empty">おすすめ商品が登録されていません。</div>'; }
  function itemCard(row){const v=row.product_variant||{},p=v.product||{},media=(v.media||[])[0],image=media?.public_url?`<img src="${escapeHtml(media.public_url)}" alt="${escapeHtml(p.product_name||"おすすめ商品")}">`:'<div class="cos-placeholder" aria-hidden="true">✦</div>'; const detail=p.catalog_slug?appendQuery(config.PRODUCT_PAGE||"product.html",{slug:p.catalog_slug}):""; return `<article class="cos-recommend-item"><div class="cos-recommend-image">${image}</div><div><div class="cos-chip-row"><span class="cos-chip gold">${escapeHtml(p.category||"おすすめ")}</span>${row.customer_response&&row.customer_response!=="unanswered"?`<span class="cos-chip">回答済み</span>`:""}</div><h2 style="margin:8px 0 4px">${detail?`<a href="${escapeHtml(detail)}">${escapeHtml(p.product_name||"商品")}</a>`:escapeHtml(p.product_name||"商品")}</h2><p>${escapeHtml(v.variant_name||v.color_name||v.size_label||"")} ${v.price_yen?`｜${escapeHtml(formatYen(v.price_yen))}`:""}</p><p><strong>おすすめ理由</strong><br>${escapeHtml(row.recommendation_reason||"お客様に合わせて選びました。")}</p>${row.usage_tip?`<p><strong>おすすめの使い方</strong><br>${escapeHtml(row.usage_tip)}</p>`:""}${row.staff_comment?`<p><strong>スタッフから</strong><br>${escapeHtml(row.staff_comment)}</p>`:""}<div class="cos-response-grid">${Object.entries(responseLabels).map(([value,label])=>`<button class="cos-response ${row.customer_response===value?"selected":""}" type="button" data-response="${value}" data-item-id="${row.id}">${escapeHtml(label)}</button>`).join("")}</div></div></article>`; }
  async function respond(event){const button=event.target.closest("[data-response]");if(!button)return;button.disabled=true;try{await request("/recommendations/respond",{method:"POST",body:{token,item_id:button.dataset.itemId,customer_response:button.dataset.response}}); const item=recommendation.items.find((v)=>v.id===button.dataset.itemId);if(item)item.customer_response=button.dataset.response;render();showToast("店舗へ回答を送りました。");}catch(e){showToast(e.message)}finally{button.disabled=false;} }
  function fail(message){$("recommendLoading").hidden=true;$("recommendError").textContent=message;$("recommendError").hidden=false;}
})();
